FROM julitopower/python36emacs25elpy

ADD kernel /opt/kernel
WORKDIR /opt/kernel
RUN python -m pip install -r requirements.txt

# Install nodejs 10.x
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN apt-get install -y nodejs

WORKDIR /opt/src/
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0"]
