version: "2"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: jupyter-server
    container_name: jupyter-server
    ports:
     - "9888:8888"
    volumes:
     - ./:/opt/dev/
    environment:
      KG_URL: http://jupyter-kernel:8888
      KG_AUTH_TOKEN: colonels
    command: >
      jupyter lab
      --NotebookApp.ip=0.0.0.0
      --NotebookApp.session_manager_class=nb2kg.managers.SessionManager
      --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager
      --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager
      --allow-root

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
    image: jupyter-kernel
    container_name: jupyter-kernel
    ports:
     - "9889:8888"
    volumes:
     - ./:/opt/dev/
    environment:
      KG_ALLOW_ORIGIN: '*'
      KG_LIST_KERNELS: "True"
      KG_AUTH_TOKEN: colonels
    command: >
      jupyter kernelgateway
      --KernelGatewayApp.ip=0.0.0.0
      --KernelGatewayApp.log_level=DEBUG
